### ISSUE TITLE
Open picker from external button(without the textview)

### ISSUE THREAD

**Issue by dudipsh** [SchoolSquirrel/nativescript-plugins#48]
Hey, thanks for the plugin...

Im wondering if there is a way to open the emoji picker from an external button as see in whatsapp and listen to the select emoji event without your default textview... 

![Screen Shot 2020-11-09 at 21 11 19](https://user-images.githubusercontent.com/6501567/98585575-2d17ab80-22d0-11eb-92f7-3b329d0900d3.png)

![Screen Shot 2020-11-09 at 21 10 12](https://user-images.githubusercontent.com/6501567/98585462-fd68a380-22cf-11eb-8fd8-bfa94407e3b1.png)

thanks

**Comment by hrueger** [comment]
Hi @dudipsh,
You will need the text input field because this is the element responsible for opening the picker (actually an requirement of the https://github.com/vanniktech/Emoji library this plugin uses).
However, you could style the toggle button just like in WhatsApp. Is that what you're trying to achieve? Or are you trying to include the picker in another element like a tab view?

**Comment by dudipsh** [comment]
![image](https://user-images.githubusercontent.com/6501567/98710409-4847f100-238c-11eb-9d5a-68433b24a2c8.png)

Hi @hrueger ,
The outcome im looking for is to be able to open the keyboard from the input textview and only when I press the emoji icon will the emoji picker open, do you think this is possible?

**Comment by hrueger** [comment]
@dudipsh Yes, sure! That's the way I'm using it, too. Did you have a look at the example on the Readme? You just have to restyle the `Toggle` button according to your needs (so rounded corners, icon instead of text, positioning). Replace your `TextField` with `<EmojiPicker>`. As `EmojiPicker` extends the `TextField` class, you should be able to use placeholders, etc just like with `TextField`.

**Comment by dudipsh** [comment]
Thank you!
I'll check it out

**Comment by dudipsh** [comment]
@hrueger 

as a work around i used TextView and copy the emoji from (myEmojiPicker) every text change

```typescript
    ngAfterViewInit(): void {

        this.globalInstance = this.renderer.listen(this.myEmojiPicker.nativeElement, 'textChange', (val) => {
            this.selectedMessage.text += this.myEmojiPicker.nativeElement.text
           this.myEmojiPicker.nativeElement.text = '';
        });

        this.globalInstance2 = this.renderer.listen(this.tv.nativeElement, 'textChange', (val) => {
            this.selectedMessage.text = val.value
        });
    }

```
thanks  for the plugin + help
